### ISSUE TITLE
Extension cannot open, not edit resX files

### ISSUE THREAD

**Issue by Mrcubix** [pmahend1/resxpress#96]
Currently getting this when creating new resx files : 

![image](https://github.com/user-attachments/assets/5bc9c9f9-1a3b-4049-bcec-59a945193768)

And this when trying to open existing resx files : 

```cs
ERR Error: Assertion Failed: argument is undefined or null
    at b (types.ts:99:9)
    at y.resolve (customEditorInput.ts:340:36)
    at async n.setInput (webviewEditor.ts:153:3)
    at async o.S (editorPanes.ts:434:4)
    at async o.L (editorPanes.ts:254:34)
    at async o.openEditor (editorPanes.ts:131:11)
    at async editorGroupView.ts:1277:49
    at async d.value (explorerView.ts:526:6)
```

As for the rare occasion where opening a known working rex file worked : 

```
webpanelScript.js:1 - Uncaught ReferenceError: module is not defined
    at webpanelScript.js:1:6805
    at webpanelScript.js:1:6809
```

Among other errors like
```
index.html?id=27e2de…F%2Fvscode-app:1060 - Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' https://*.vscode-cdn.net". Either the 'unsafe-inline' keyword, a hash ('sha256-Wi3+8jbn12vus9Oq4FOqEUCOpuRG3clBaVvLZZ2b9Fs='), or a nonce ('nonce-...') is required to enable inline execution. Note that hashes do not apply to event handlers, style attributes and javascript: navigations unless the 'unsafe-hashes' keyword is present.
```

Never got it to work again.

Also i do not understand the point of specifying the namespace if it's not used during source generation

**Comment by pmahend1** [comment]
Looks like for some reason it is not able to read filesystem/file. I am wondering if it is due to folder name `C#` containing special character.

Can you check if it gets resolved if you rename it to `Csharp`?

Adding namespace is because C# resource file would be generated with the namespace, this helps avoid relying on hard on `resgen` which is available in .Net framework only.

**Comment by Mrcubix** [comment]
Using a hardlink instead for this, as i don't want to break other projects, but anyway, result in this instead : 

```
Error loading webview: Error: Could not register service worker: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state..
```

![image](https://github.com/user-attachments/assets/00e43b8c-19df-4cf8-9f7d-62eb7ead9152)

**Comment by pmahend1** [comment]
I will try to reproduce it on Windows.

**Comment by Mrcubix** [comment]
There isn't a need to do testing on Windows for creating a resource, cause it doesn't work on linux either : 

```
ERR Error: Unable to create file '/home/pi/Documents/repos/C' that already exists when overwrite flag is not set
    at qit.u (fileService.ts:350:10)
    at async qit.canCreateFile (fileService.ts:338:4)
    at async Promise.all (index 0)
    at async Object.e [as settled] (async.ts:1644:18)
    at async NPe.doCreateFileOrFolder (workingCopyFileService.ts:344:28)
    at async Tme.perform (bulkFileEdits.ts:198:3)
    at async wqe.apply (bulkFileEdits.ts:396:20)
    at async Cqe.n (bulkEditService.ts:137:10)
    at async Cqe.perform (bulkEditService.ts:120:20)
    at async Sqe.apply (bulkEditService.ts:245:22)
```

**Comment by pmahend1** [comment]
@Mrcubix The issue got closed automatically when I mentioned it in the PR. Please let me know if the issue still recurs.

**Comment by Mrcubix** [comment]
Creating, Reading & editing seems to now work properly on Windows

I however noticed that this peculiar warning appeared : 

![image](https://github.com/user-attachments/assets/a9690df8-e319-47f2-9395-163869b6288e)

**Comment by pmahend1** [comment]
I noticed that too. Not sure if it is due to webpack or tsconfig. It's not causing issues, so all good for now. 😄
